### ISSUE TITLE
Basic Card

### ISSUE THREAD

**Issue by 20dakshayani** [20dakshayani/Team67#3]
@1269mahima create a Basic Card using material -ui in react

**Comment by 1269mahima** [comment]
In App.js

import * as React from 'react';
import { Card } from '@material-ui/core';
import { CardContent } from '@material-ui/core';
import { CardMedia } from '@material-ui/core';
import { Typography } from '@material-ui/core';
export default function MediaCard() {
  return (
    <Card style={{width: 400,height: 600, marginLeft: 500,marginRight: 500, marginTop: 100, backgroundColor:'pink',border:"5px solid skyblue" }}>

      <center><CardMedia
        component="img"
        height="150"
        style={{ width: 300,height: 300,marginTop: 20,borderRadius:1000 }}
        image="https://cliparting.com/wp-content/uploads/2018/03/cartoon-girl-2018-46.png"
        alt="girl image"
      />
</center>
      <CardContent>
        <Typography gutterBottom variant="h5" component="div">
           <center>Frontend developer</center>
        </Typography>
        <Typography variant="body2" color="text.secondary">
          <center>Yalamati Mahima</center><br></br>
          <center>Frond End developer</center><br></br>
          <center>CSE Department,KL university</center><br></br>
          <center>From vijayawada</center>
        </Typography>
      </CardContent>
    </Card>
  );
}


![image](https://user-images.githubusercontent.com/99397493/183243778-559c109f-e3bd-41c5-a5f9-c691d7a7f3e2.png)

**Comment by 1269mahima** [comment]
The above code gives a basic card with material-ui

**Comment by 2003chandini** [comment]
Perfect information of a basic card

**Comment by 20dakshayani** [comment]
This is using material-ui
