### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by 20dakshayani** [20dakshayani/Team67#4]
@2003chandini create a menu for breakfast in KLMART

**Comment by 2003chandini** [comment]
import logo from './logo.svg';
import './App.css';
import Menu from './Components/Menu';
import Breakfast from './Components/Breakfast';
import Lunch from './Components/Lunch';
import Snacks from './Components/Snacks';
import Dinner from './Components/Dinner';
import Deserts from './Components/Deserts';
import Forms from './Components/Forms';


function App() {
  return (
    <div className="App">
     <Menu></Menu>
     <Forms></Forms>

     <Breakfast></Breakfast>
     <Lunch></Lunch>
     <Snacks></Snacks>
     <Dinner></Dinner>
     <Deserts></Deserts>
    </div>
  );
}
export default App
![Screenshot (85)](https://user-images.githubusercontent.com/99397300/183243726-c87ad5e7-5eee-472a-af87-807d67f07dc9.png)
![Screenshot (86)](https://user-images.githubusercontent.com/99397300/183243741-95ee367e-4ddb-4151-a51c-8cdaf87fcbba.png)

**Comment by 2003chandini** [comment]
Menu of Kl Mart
